/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VillaService } from "../villa.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VillaCreateInput } from "./VillaCreateInput";
import { Villa } from "./Villa";
import { VillaFindManyArgs } from "./VillaFindManyArgs";
import { VillaWhereUniqueInput } from "./VillaWhereUniqueInput";
import { VillaUpdateInput } from "./VillaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VillaControllerBase {
  constructor(
    protected readonly service: VillaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Villa })
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVilla(@common.Body() data: VillaCreateInput): Promise<Villa> {
    return await this.service.createVilla({
      data: data,
      select: {
        amenities: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        pricePerNight: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Villa] })
  @ApiNestedQuery(VillaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async villas(@common.Req() request: Request): Promise<Villa[]> {
    const args = plainToClass(VillaFindManyArgs, request.query);
    return this.service.villas({
      ...args,
      select: {
        amenities: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        pricePerNight: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Villa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async villa(
    @common.Param() params: VillaWhereUniqueInput
  ): Promise<Villa | null> {
    const result = await this.service.villa({
      where: params,
      select: {
        amenities: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        pricePerNight: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Villa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVilla(
    @common.Param() params: VillaWhereUniqueInput,
    @common.Body() data: VillaUpdateInput
  ): Promise<Villa | null> {
    try {
      return await this.service.updateVilla({
        where: params,
        data: data,
        select: {
          amenities: true,
          createdAt: true,
          id: true,
          location: true,
          name: true,
          pricePerNight: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Villa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVilla(
    @common.Param() params: VillaWhereUniqueInput
  ): Promise<Villa | null> {
    try {
      return await this.service.deleteVilla({
        where: params,
        select: {
          amenities: true,
          createdAt: true,
          id: true,
          location: true,
          name: true,
          pricePerNight: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
