/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Villa } from "./Villa";
import { VillaCountArgs } from "./VillaCountArgs";
import { VillaFindManyArgs } from "./VillaFindManyArgs";
import { VillaFindUniqueArgs } from "./VillaFindUniqueArgs";
import { CreateVillaArgs } from "./CreateVillaArgs";
import { UpdateVillaArgs } from "./UpdateVillaArgs";
import { DeleteVillaArgs } from "./DeleteVillaArgs";
import { VillaService } from "../villa.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Villa)
export class VillaResolverBase {
  constructor(
    protected readonly service: VillaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "read",
    possession: "any",
  })
  async _villasMeta(
    @graphql.Args() args: VillaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Villa])
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "read",
    possession: "any",
  })
  async villas(@graphql.Args() args: VillaFindManyArgs): Promise<Villa[]> {
    return this.service.villas(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Villa, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "read",
    possession: "own",
  })
  async villa(
    @graphql.Args() args: VillaFindUniqueArgs
  ): Promise<Villa | null> {
    const result = await this.service.villa(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Villa)
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "create",
    possession: "any",
  })
  async createVilla(@graphql.Args() args: CreateVillaArgs): Promise<Villa> {
    return await this.service.createVilla({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Villa)
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "update",
    possession: "any",
  })
  async updateVilla(
    @graphql.Args() args: UpdateVillaArgs
  ): Promise<Villa | null> {
    try {
      return await this.service.updateVilla({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Villa)
  @nestAccessControl.UseRoles({
    resource: "Villa",
    action: "delete",
    possession: "any",
  })
  async deleteVilla(
    @graphql.Args() args: DeleteVillaArgs
  ): Promise<Villa | null> {
    try {
      return await this.service.deleteVilla(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
